import type { Product, Category, Order } from "@/types"

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Cuadernos",
    slug: "cuadernos",
    image: "/assorted-notebooks.png",
    productCount: 12,
  },
  {
    id: "2",
    name: "Lápices y Bolígrafos",
    slug: "lapices-boligrafos",
    image: "/pens-and-pencils.jpg",
    productCount: 15,
  },
  {
    id: "3",
    name: "Mochilas",
    slug: "mochilas",
    image: "/backpacks.jpg",
    productCount: 10,
  },
  {
    id: "4",
    name: "Arte y Manualidades",
    slug: "arte-manualidades",
    image: "/art-supplies-still-life.png",
    productCount: 14,
  },
  {
    id: "5",
    name: "Organización",
    slug: "organizacion",
    image: "/school-organization.jpg",
    productCount: 12,
  },
  {
    id: "6",
    name: "Tecnología",
    slug: "tecnologia",
    image: "/school-technology.jpg",
    productCount: 12,
  },
]

export const mockProducts: Product[] = [
  // Cuadernos (12 productos)
  {
    id: "1",
    name: "Cuaderno Universitario 100 Hojas",
    slug: "cuaderno-universitario-100-hojas",
    description: "Cuaderno universitario de 100 hojas con espiral, ideal para tomar apuntes.",
    price: 4.99,
    category: "cuadernos",
    brand: "Norma",
    stock: 150,
    images: ["/open-notebook-desk.png"],
    rating: 4.5,
    reviews: 128,
    featured: true,
  },
  {
    id: "7",
    name: "Cuaderno Espiral A4 200 Hojas",
    slug: "cuaderno-espiral-a4-200-hojas",
    description: "Cuaderno grande con tapa dura y 200 hojas cuadriculadas.",
    price: 7.99,
    category: "cuadernos",
    brand: "Norma",
    stock: 85,
    images: ["/spiral-notebook-a4.jpg"],
    rating: 4.6,
    reviews: 92,
    featured: true,
  },
  {
    id: "8",
    name: "Cuaderno Cosido Pasta Dura",
    slug: "cuaderno-cosido-pasta-dura",
    description: "Cuaderno profesional con pasta dura y hojas rayadas.",
    price: 6.49,
    category: "cuadernos",
    brand: "Scribe",
    stock: 110,
    images: ["/hardcover-notebook.jpg"],
    rating: 4.7,
    reviews: 156,
    featured: false,
  },
  {
    id: "9",
    name: "Block de Notas Adhesivas",
    slug: "block-notas-adhesivas",
    description: "Pack de 5 blocks de notas adhesivas en colores variados.",
    price: 3.99,
    category: "cuadernos",
    brand: "Post-it",
    stock: 200,
    images: ["/sticky-notes-colorful.jpg"],
    rating: 4.8,
    reviews: 234,
    featured: false,
  },
  {
    id: "10",
    name: "Libreta de Dibujo A3",
    slug: "libreta-dibujo-a3",
    description: "Libreta de hojas blancas especial para dibujo y bocetos.",
    price: 9.99,
    category: "cuadernos",
    brand: "Canson",
    stock: 65,
    images: ["/sketchbook-a3.jpg"],
    rating: 4.9,
    reviews: 87,
    featured: false,
  },
  {
    id: "11",
    name: "Cuaderno Inteligente Reutilizable",
    slug: "cuaderno-inteligente-reutilizable",
    description: "Cuaderno digital que puedes escanear y borrar para reutilizar.",
    price: 29.99,
    category: "cuadernos",
    brand: "Rocketbook",
    stock: 45,
    images: ["/smart-reusable-notebook.jpg"],
    rating: 4.4,
    reviews: 67,
    featured: true,
  },

  // Lápices y Bolígrafos (15 productos)
  {
    id: "2",
    name: "Set de Bolígrafos x 12 Colores",
    slug: "set-boligrafos-12-colores",
    description: "Set de 12 bolígrafos de colores variados, perfectos para estudiantes.",
    price: 8.99,
    category: "lapices-boligrafos",
    brand: "Bic",
    stock: 200,
    images: ["/colorful-pens.jpg"],
    rating: 4.8,
    reviews: 256,
    featured: true,
  },
  {
    id: "12",
    name: "Lápices Grafito HB x 12",
    slug: "lapices-grafito-hb-12",
    description: "Caja de 12 lápices de grafito HB con borrador incluido.",
    price: 5.99,
    category: "lapices-boligrafos",
    brand: "Faber-Castell",
    stock: 180,
    images: ["/graphite-pencils-box.jpg"],
    rating: 4.7,
    reviews: 189,
    featured: false,
  },
  {
    id: "13",
    name: "Marcadores Permanentes x 6",
    slug: "marcadores-permanentes-6",
    description: "Set de 6 marcadores permanentes punta fina en colores básicos.",
    price: 7.49,
    category: "lapices-boligrafos",
    brand: "Sharpie",
    stock: 145,
    images: ["/permanent-markers-fine-tip.jpg"],
    rating: 4.9,
    reviews: 312,
    featured: true,
  },
  {
    id: "14",
    name: "Resaltadores Fluorescentes x 4",
    slug: "resaltadores-fluorescentes-4",
    description: "Pack de 4 resaltadores en colores amarillo, verde, naranja y rosa.",
    price: 4.49,
    category: "lapices-boligrafos",
    brand: "Stabilo",
    stock: 220,
    images: ["/fluorescent-highlighters.jpg"],
    rating: 4.8,
    reviews: 278,
    featured: false,
  },
  {
    id: "15",
    name: "Plumas Estilográficas Premium",
    slug: "plumas-estilograficas-premium",
    description: "Set de 2 plumas estilográficas con cartuchos de tinta incluidos.",
    price: 18.99,
    category: "lapices-boligrafos",
    brand: "Parker",
    stock: 55,
    images: ["/fountain-pens-premium.jpg"],
    rating: 4.6,
    reviews: 94,
    featured: false,
  },
  {
    id: "16",
    name: "Portaminas 0.7mm + Minas",
    slug: "portaminas-07mm-minas",
    description: "Portaminas profesional con estuche de minas de repuesto.",
    price: 6.99,
    category: "lapices-boligrafos",
    brand: "Pentel",
    stock: 125,
    images: ["/mechanical-pencil-0-7mm.jpg"],
    rating: 4.7,
    reviews: 167,
    featured: false,
  },

  // Mochilas (10 productos)
  {
    id: "3",
    name: "Mochila Escolar Resistente",
    slug: "mochila-escolar-resistente",
    description: "Mochila de alta resistencia con múltiples compartimentos.",
    price: 45.99,
    category: "mochilas",
    brand: "Totto",
    stock: 75,
    images: ["/bag.png"],
    rating: 4.7,
    reviews: 89,
    featured: true,
  },
  {
    id: "17",
    name: "Mochila con Puerto USB",
    slug: "mochila-puerto-usb",
    description: "Mochila moderna con puerto USB para cargar dispositivos y compartimento para laptop.",
    price: 54.99,
    category: "mochilas",
    brand: "Samsonite",
    stock: 60,
    images: ["/backpack-usb-port-laptop.jpg"],
    rating: 4.8,
    reviews: 145,
    featured: true,
  },
  {
    id: "18",
    name: "Morral Deportivo Impermeable",
    slug: "morral-deportivo-impermeable",
    description: "Morral ligero e impermeable ideal para deportes y actividades al aire libre.",
    price: 32.99,
    category: "mochilas",
    brand: "Nike",
    stock: 95,
    images: ["/waterproof-sports-bag.jpg"],
    rating: 4.6,
    reviews: 112,
    featured: false,
  },
  {
    id: "19",
    name: "Lonchera Térmica",
    slug: "lonchera-termica",
    description: "Lonchera térmica con aislamiento para mantener alimentos frescos.",
    price: 15.99,
    category: "mochilas",
    brand: "Thermos",
    stock: 130,
    images: ["/thermal-lunch-bag.jpg"],
    rating: 4.5,
    reviews: 87,
    featured: false,
  },
  {
    id: "20",
    name: "Mochila Mini Urbana",
    slug: "mochila-mini-urbana",
    description: "Mochila compacta perfecta para salidas cortas y uso diario.",
    price: 28.99,
    category: "mochilas",
    brand: "Herschel",
    stock: 85,
    images: ["/mini-urban-backpack.jpg"],
    rating: 4.7,
    reviews: 156,
    featured: false,
  },

  // Arte y Manualidades (14 productos)
  {
    id: "4",
    name: "Set de Acuarelas 24 Colores",
    slug: "set-acuarelas-24-colores",
    description: "Set profesional de acuarelas con 24 colores vibrantes.",
    price: 15.99,
    category: "arte-manualidades",
    brand: "Faber-Castell",
    stock: 120,
    images: ["/watercolor-paint-set.jpg"],
    rating: 4.9,
    reviews: 178,
    featured: true,
  },
  {
    id: "21",
    name: "Crayones x 48 Colores",
    slug: "crayones-48-colores",
    description: "Caja de 48 crayones de colores con sacapuntas incluido.",
    price: 12.99,
    category: "arte-manualidades",
    brand: "Crayola",
    stock: 165,
    images: ["/crayons-48-colors-box.jpg"],
    rating: 4.8,
    reviews: 234,
    featured: false,
  },
  {
    id: "22",
    name: "Set de Pinceles Profesionales",
    slug: "set-pinceles-profesionales",
    description: "Kit de 12 pinceles de diferentes tamaños para pintura artística.",
    price: 19.99,
    category: "arte-manualidades",
    brand: "Royal & Langnickel",
    stock: 78,
    images: ["/professional-paint-brushes.png"],
    rating: 4.7,
    reviews: 92,
    featured: false,
  },
  {
    id: "23",
    name: "Tijeras Escolares Punta Roma",
    slug: "tijeras-escolares-punta-roma",
    description: "Tijeras seguras con punta roma, ideales para niños.",
    price: 2.99,
    category: "arte-manualidades",
    brand: "Maped",
    stock: 250,
    images: ["/safety-scissors-blunt-tip.jpg"],
    rating: 4.6,
    reviews: 189,
    featured: false,
  },
  {
    id: "24",
    name: "Pegamento Líquido 250ml",
    slug: "pegamento-liquido-250ml",
    description: "Pegamento blanco líquido no tóxico, lavable y de secado rápido.",
    price: 3.49,
    category: "arte-manualidades",
    brand: "Elmer's",
    stock: 200,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.5,
    reviews: 145,
    featured: false,
  },
  {
    id: "25",
    name: "Plastilina 12 Colores",
    slug: "plastilina-12-colores",
    description: "Set de plastilina no tóxica en 12 colores brillantes.",
    price: 8.99,
    category: "arte-manualidades",
    brand: "Play-Doh",
    stock: 140,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.7,
    reviews: 201,
    featured: false,
  },
  {
    id: "26",
    name: "Cartulinas de Colores x 50",
    slug: "cartulinas-colores-50",
    description: "Paquete de 50 cartulinas en colores surtidos tamaño carta.",
    price: 11.99,
    category: "arte-manualidades",
    brand: "Iris",
    stock: 95,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.4,
    reviews: 76,
    featured: false,
  },

  // Organización (12 productos)
  {
    id: "5",
    name: "Organizador de Escritorio",
    slug: "organizador-escritorio",
    description: "Organizador multifuncional para mantener ordenado tu espacio de estudio.",
    price: 12.99,
    category: "organizacion",
    brand: "Office Max",
    stock: 95,
    images: ["/desk-organizer.png"],
    rating: 4.4,
    reviews: 64,
    featured: false,
  },
  {
    id: "27",
    name: "Carpeta con Argollas 3 Pulgadas",
    slug: "carpeta-argollas-3-pulgadas",
    description: "Carpeta resistente con argollas de 3 pulgadas y bolsillos interiores.",
    price: 8.99,
    category: "organizacion",
    brand: "Wilson Jones",
    stock: 120,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.6,
    reviews: 98,
    featured: false,
  },
  {
    id: "28",
    name: "Separadores con Pestañas x 12",
    slug: "separadores-pestanas-12",
    description: "Set de 12 separadores con pestañas de colores para organizar documentos.",
    price: 4.99,
    category: "organizacion",
    brand: "Avery",
    stock: 180,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.5,
    reviews: 123,
    featured: false,
  },
  {
    id: "29",
    name: "Archivador Acordeón 12 Divisiones",
    slug: "archivador-acordeon-12-divisiones",
    description: "Archivador expandible con 12 divisiones y cierre elástico.",
    price: 14.99,
    category: "organizacion",
    brand: "Pendaflex",
    stock: 75,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.7,
    reviews: 87,
    featured: false,
  },
  {
    id: "30",
    name: "Porta Documentos con Cierre",
    slug: "porta-documentos-cierre",
    description: "Sobre de plástico con cierre para proteger documentos importantes.",
    price: 2.49,
    category: "organizacion",
    brand: "Staples",
    stock: 300,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.3,
    reviews: 156,
    featured: false,
  },
  {
    id: "31",
    name: "Agenda Académica 2025",
    slug: "agenda-academica-2025",
    description: "Agenda semanal con calendario completo y secciones para planificación.",
    price: 16.99,
    category: "organizacion",
    brand: "Moleskine",
    stock: 85,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.8,
    reviews: 134,
    featured: true,
  },

  // Tecnología (12 productos)
  {
    id: "6",
    name: "Calculadora Científica",
    slug: "calculadora-cientifica",
    description: "Calculadora científica con funciones avanzadas para matemáticas.",
    price: 24.99,
    category: "tecnologia",
    brand: "Casio",
    stock: 60,
    images: ["/scientific-calculator.jpg"],
    rating: 4.6,
    reviews: 142,
    featured: true,
  },
  {
    id: "32",
    name: "USB 3.0 64GB",
    slug: "usb-30-64gb",
    description: "Memoria USB de alta velocidad con 64GB de capacidad.",
    price: 14.99,
    category: "tecnologia",
    brand: "SanDisk",
    stock: 150,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.7,
    reviews: 298,
    featured: false,
  },
  {
    id: "33",
    name: "Mouse Inalámbrico",
    slug: "mouse-inalambrico",
    description: "Mouse ergonómico inalámbrico con batería de larga duración.",
    price: 19.99,
    category: "tecnologia",
    brand: "Logitech",
    stock: 110,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.8,
    reviews: 234,
    featured: true,
  },
  {
    id: "34",
    name: "Auriculares con Micrófono",
    slug: "auriculares-microfono",
    description: "Auriculares con micrófono integrado perfectos para clases virtuales.",
    price: 29.99,
    category: "tecnologia",
    brand: "Sony",
    stock: 85,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.6,
    reviews: 187,
    featured: false,
  },
  {
    id: "35",
    name: "Lámpara LED de Escritorio",
    slug: "lampara-led-escritorio",
    description: "Lámpara LED ajustable con 3 niveles de brillo y puerto USB.",
    price: 34.99,
    category: "tecnologia",
    brand: "Philips",
    stock: 70,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.7,
    reviews: 156,
    featured: false,
  },
  {
    id: "36",
    name: "Cargador Múltiple 4 Puertos",
    slug: "cargador-multiple-4-puertos",
    description: "Cargador de pared con 4 puertos USB para cargar múltiples dispositivos.",
    price: 22.99,
    category: "tecnologia",
    brand: "Anker",
    stock: 125,
    images: ["/placeholder.svg?height=400&width=400"],
    rating: 4.9,
    reviews: 412,
    featured: true,
  },
]

export const mockOrders: Order[] = [
  {
    id: "ORD-1702345678901",
    userId: "user-demo",
    items: [
      {
        productId: "1",
        name: "Cuaderno Universitario 100 Hojas",
        price: 4.99,
        quantity: 3,
        image: "/open-notebook-desk.png",
      },
      {
        productId: "2",
        name: "Set de Bolígrafos x 12 Colores",
        price: 8.99,
        quantity: 2,
        image: "/colorful-pens.jpg",
      },
    ],
    subtotal: 32.95,
    shipping: 5.0,
    total: 37.95,
    status: "delivered",
    shippingAddress: {
      fullName: "María González",
      street: "Calle Principal 123",
      city: "Buenos Aires",
      state: "CABA",
      zipCode: "1425",
      country: "Argentina",
    },
    paymentMethod: "card",
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ORD-1702345678902",
    userId: "user-demo",
    items: [
      {
        productId: "3",
        name: "Mochila Escolar Resistente",
        price: 45.99,
        quantity: 1,
        image: "/bag.png",
      },
    ],
    subtotal: 45.99,
    shipping: 0,
    total: 45.99,
    status: "processing",
    shippingAddress: {
      fullName: "María González",
      street: "Calle Principal 123",
      city: "Buenos Aires",
      state: "CABA",
      zipCode: "1425",
      country: "Argentina",
    },
    paymentMethod: "card",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ORD-1702345678903",
    userId: "user-demo",
    items: [
      {
        productId: "4",
        name: "Set de Acuarelas 24 Colores",
        price: 15.99,
        quantity: 1,
        image: "/watercolor-paint-set.jpg",
      },
      {
        productId: "6",
        name: "Calculadora Científica",
        price: 24.99,
        quantity: 1,
        image: "/scientific-calculator.jpg",
      },
    ],
    subtotal: 40.98,
    shipping: 5.0,
    total: 45.98,
    status: "shipped",
    shippingAddress: {
      fullName: "María González",
      street: "Calle Principal 123",
      city: "Buenos Aires",
      state: "CABA",
      zipCode: "1425",
      country: "Argentina",
    },
    paymentMethod: "transfer",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
